# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |  # runs during prebuild
      pip install poetry 
      export PIP_USER=false 
      poetry config cache-dir /workspace/.cache/pypoetry 
      poetry update
    command: flask run

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000
    onOpen: open-preview
